version: "3.9"
name: nodejs-stack
serviices:
  nodejs:
   build:
   ports:
   - 3001:3000
   networks:
   - my-network
   depends_on:
   - mongodb
mongodb:
   image: mongo:Latest
   restart: unless-stopped
   ports:
   - 27018:27017
   volumes:
   - db:/data/db  
volumes:
   db:   

